logicisaliar/boat-bnb

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
Navbar and footer copied from Le Wagon - Jash
> Navbar and footer copied from Le Wagon

- app/models/boat.rb
- app/models/user.rb
- db/migrate/20180618175612_create_boats.rb
- db/schema.rb
- test/models/boat_test.rb
Hey Jash, can you check up this and merge it please? 
I have added  has_many :boats in the user model(Joti's).
> boat model created with association to user

- db/migrate/20180618174545_add_fields_to_users.rb
- db/schema.rb
Hey Jefe! Look my awsome changes! ;)
ACCEPT IT MOTHERFUCKR!!!!!!!!!!!!!!!!!!!!!!!!!!!
> added new columns to user table

- app/models/boat.rb
- app/models/booking.rb
- app/models/user.rb
- db/migrate/20180618175612_create_boats.rb
- db/migrate/20180618202124_create_bookings.rb
- db/schema.rb
- test/models/booking_test.rb
Jash,
Please merge this piece of code. It's already tested and working.
Thanks!
Luli
> booking model & associations done and tested

- db/schema.rb
> Migration changed - type ---> boat_type

- app/models/boat.rb
- app/models/booking.rb
- app/models/user.rb
- db/migrate/20180618202124_create_bookings.rb
Validations done. So enjoy that shizz.
> Done the validations.

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/pages/become_host.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
Home page and some other things added in 'Become a host'.
> Home pages beautified.

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
hey guys!
TO HAVE IN CONSIDERATION:
1) NO STYLE HAS BEEN GIVEN TO THE NAVBAR CHANGES
2) WE SHOULD (I DIDNT KNEW HOW TO DO IT) CHANGE THE NAVBAR OPTION DEPENDING IF A PERSON IS ALREADY LOGGED IN
3) I ADDED LOGOUT IN THE BURGER MENU (IT WORKS ;) )
4) THE REDIRECTION OF THE BECOME A HOST AND LOGIN WORKS.
5) I love you
> added became a host & sign in options in navbar

- app/controllers/boats_controller.rb
- app/controllers/bookings_controller.rb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- booking summery without style
- calculation done (to integer. maybe it should be with float) feel free to change it
- confirmation button done but we dont have a route nor nothing to the checkout/payments
> booking summery done (total price depending in quantity of days done

- app/views/shared/_navbar.html.erb
if you are logged in, you have an avatar with a dropdown menu with "my boats", "requests" and 'logout' options. 
if you are not logged in you have the 'become a host' and 'sign in' option
> navbar authentication done

- app/controllers/boats_controller.rb
now you can see a boat description without the obligation of being logged in
> removed login before clicking boat description

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/boats_controller.rb
- app/controllers/host/boats_controller.rb
- app/policies/application_policy.rb
- app/policies/boat_policy.rb
- app/views/host/boats/edit.html.erb
- app/views/host/boats/index.html.erb
- app/views/host/boats/show.html.erb
- test/policies/boat_policy_test.rb
I have finished the pund it for boats and already test edit, delete and create.
> pundit for boats ok, already tested

- app/views/layouts/application.html.erb
just changed the name of the tab form TODO to Boatbnb
> title changed to Boatbnb

- app/controllers/host/boats_controller.rb
- app/models/boat.rb
- app/views/boats/show.html.erb
- app/views/host/boats/_form.html.erb
- app/views/host/boats/show.html.erb
> Photoshow bug

- app/views/host/boats/index.html.erb
- db/schema.rb
I have added buttons into the hosts boats index so to view the details of the boat and to create a new boat
> buttons into the index of host/boats:  new boat and show

- app/controllers/bookings_controller.rb
- app/policies/booking_policy.rb
- config/database.yml
- test/policies/booking_policy_test.rb
> Booking pundit

- db/seeds.rb
@logicisaliar please remember to commit the change in the schema so it doesn't show again. 
Also, rails db:seed when you deploy.
Thanks!
> update of the seeds adding the 9th name so we have 9 cards

- app/assets/stylesheets/pages/_become_host.scss
- app/views/pages/become_host.html.erb
- app/views/pages/home.html.erb
the only thing its missing is the go in the same line
> home and become host home done

- app/assets/stylesheets/layouts/_index.scss
- app/assets/stylesheets/layouts/booking_form.scss
- app/views/bookings/new.html.erb
Booking page with data selector done.
> booking form (dates) ok with style (70%)

- app/assets/stylesheets/layouts/confirmation.scss
- app/views/bookings/show.html.erb
New name for container son it doen't mix with the component.
Sorry!!
> New name to class container: conf-container

- app/views/boats/search_by_city.html.erb
> Map style3
